package pojo;
// Generated 25 nov. 2022 12:10:59 by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;

/**
 * Animales generated by hbm2java
 */
public class Animales implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String habitat;
	private BigDecimal pesoAprox;

	public Animales() {
	}

	public Animales(String nombre, String habitat, BigDecimal pesoAprox) {
		this.nombre = nombre;
		this.habitat = habitat;
		this.pesoAprox = pesoAprox;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHabitat() {
		return this.habitat;
	}

	public void setHabitat(String habitat) {
		this.habitat = habitat;
	}

	public BigDecimal getPesoAprox() {
		return this.pesoAprox;
	}

	public void setPesoAprox(BigDecimal pesoAprox) {
		this.pesoAprox = pesoAprox;
	}

}
