package pojo.pojo;
// Generated 25 nov. 2022 14:23:28 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Series generated by hbm2java
 */
public class Series implements java.io.Serializable {

	private Integer id;
	private String titulo;
	private Integer edad;
	private String plataforma;
	private Set temporadases = new HashSet(0);

	public Series() {
	}

	public Series(String titulo) {
		this.titulo = titulo;
	}

	public Series(String titulo, Integer edad, String plataforma, Set temporadases) {
		this.titulo = titulo;
		this.edad = edad;
		this.plataforma = plataforma;
		this.temporadases = temporadases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public String getPlataforma() {
		return this.plataforma;
	}

	public void setPlataforma(String plataforma) {
		this.plataforma = plataforma;
	}

	public Set getTemporadases() {
		return this.temporadases;
	}

	public void setTemporadases(Set temporadases) {
		this.temporadases = temporadases;
	}

}
